---

apache_user: 'www-data'
apache_group: 'www-data'
apache_service: apache2
apache_daemon: apache2
apache_daemon_path: '/usr/sbin/'
apache_server_root: '/etc/apache2'
apache_conf_path: '/etc/apache2'

# symlinks to mods-enabled directory required
apache_mod_symlinks: true
# symlinks to sites-enabled directory required
apache_vhost_symlinks: true
# default vhost file, will be removed if defined
apache_default_vhost_filename: '000-default.conf'

apache_packages:
  - apache2
  - apache2-utils
