---

dependencies: []

galaxy_info:
  role_name: 'pki'
  author: 'Adfinis SyGroup AG'
  description: 'Install and manage PKI packages and helpers'
  company: 'Adfinis SyGroup AG'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'
  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - pki
    - openssl
