---

# The bit size of the diffie-hellman parameter.
pki_dhparam_bits: 4096

# The file for the diffie-hellman parameter.
pki_dhparam_file: '/etc/ssl/dh{{ pki_dhparam_bits }}.pem'

# Backup system and path for certificates and keys.
# The tasks will be delegated to this system.
pki_backup:
  system: ''
  path: ''

# A list of all domains for which certificates should exist.
pki_domains: []

# Alt DNS entries can be added as well, e.g.
#
# .. code-block:: YAML
#
#   pki_domains:
#     - cert: www.example.com
#     - cert: mail.example.com
#       alt:
#         - imap.example.com
#         - smtp.example.com
#

# Certificates and keys to backup.
# Domain names within the ``pki_directory`` directory to backup.
pki_backup_domains: []

# A possible list looks like this:
#
# .. code-block:: YAML
#
#   pki_backup_domains:
#     - www.example.org
#
# This will backup the following files:
#
# - ``/etc/ssl/private/www.example.org/privkey.pem``
# - ``/etc/ssl/private/www.example.org/cert.pem``
