---

- name: install pki related packages
  package:
    name: '{{ pki_packages }}'
    state: present

- name: create directory for private keys and certificates
  file:
    path: '{{ item.path }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
    seuser: system_u
    serole: object_r
    setype: cert_t
    selevel: s0
    state: directory
  with_items: '{{ pki_directories }}'
